[workspace]
channels = ["conda-forge"]
name = "Droughts-Predictions-with-Machine-Learning"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
numpy = ">=2.3.3,<3"
pandas = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"
ipykernel = ">=6.30.1,<7"
matplotlib = ">=3.10.6,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.2,<2"
scipy = ">=1.16.2,<2"
